local format = require("/ux_overhaul/core/format.lua")

describe("format", function()
	it("abbreviates large numbers", function()
		assert.are.equal("950", format.compact(950))
		assert.are.equal("1.2k", format.compact(1234))
		assert.are.equal("1k", format.compact(1000))
		assert.are.equal("25k", format.compact(25300))
		assert.are.equal("1.2M", format.compact(1234567))
		assert.are.equal("12M", format.compact(12345678))
		assert.are.equal("\u{2212}5k", format.compact(-5000))
		assert.are.equal("0", format.compact(nil))
	end)

	it("signs balances", function()
		assert.are.equal("+1.5k", format.signed(1500))
		assert.are.equal("\u{2212}1.5k", format.signed(-1500))
		assert.are.equal("0", format.signed(0))
	end)

	it("formats ratios as percent", function()
		assert.are.equal("46%", format.percent(0.456))
		assert.are.equal("\u{2013}", format.percent(nil))
	end)
end)
