local slider_snap = require("/ui_overhaul/core/slider_snap.lua")

describe("slider_snap", function()
	it("picks round detents of about 5 % of the range", function()
		assert.are.equal(5, slider_snap.detent(0, 100, 1))
		assert.are.equal(50, slider_snap.detent(0, 600, 10))
		assert.are.equal(5, slider_snap.detent(0, 60, 1))
		assert.are.equal(25, slider_snap.detent(0, 500, 1))
		-- few steps: every step is a detent already
		assert.is_nil(slider_snap.detent(1, 16, 1))
		assert.is_nil(slider_snap.detent(0, 200, 10))
		assert.is_nil(slider_snap.detent(5, 5, 1))
	end)

	it("only uses detents the slider can reach, also for odd steps", function()
		-- step 3: 2.5 and 5 are no multiples; the result is a multiple of 3 and finite
		local d = slider_snap.detent(0, 600, 3)
		assert.are.equal(0, d % 3)
		assert.is_true(d <= 30)
		-- the game bar's sun position slider: 0..1440 in steps of 15
		local sun = slider_snap.detent(0, 1440, 15)
		assert.are.equal(0, sun % 15)
		assert.is_true(1440 / sun <= 20 and sun < 1440)
		-- a step of 7 over 0..700
		local seven = slider_snap.detent(0, 700, 7)
		assert.are.equal(0, seven % 7)
		assert.is_true(seven <= 70)
	end)

	it("counts detents from round values on the slider's grid", function()
		assert.are.equal(0, slider_snap.anchor(1, 1)) -- 1..60: snaps at 5, 10, 15
		assert.are.equal(10, slider_snap.snap(9, 1, 60, 5, slider_snap.anchor(1, 1)))
		assert.are.equal(1, slider_snap.anchor(1, 2)) -- odd values only: count from 1
		assert.are.equal(0, slider_snap.anchor(1000000, 1000000))
		assert.are.equal(5000000, slider_snap.snap(5200000, 1000000, 20000000, 5000000, 0))
	end)

	it("keeps values on the slider's grid", function()
		assert.are.equal(5, slider_snap.on_grid(4, 1, 59, 2))
		assert.are.equal(3, slider_snap.on_grid(3.2, 1, 59, 2))
		assert.are.equal(59, slider_snap.on_grid(80, 1, 59, 2))
		assert.are.equal(30, slider_snap.on_grid(31, 0, 600, 10))
	end)

	it("snaps magnetically", function()
		assert.are.equal(25, slider_snap.snap(24, 0, 100, 5))
		assert.are.equal(25, slider_snap.snap(26, 0, 100, 5))
		assert.are.equal(23, slider_snap.snap(23, 0, 100, 5)) -- two away: stays
		assert.are.equal(50, slider_snap.snap(36, 0, 600, 50)) -- 14 of 50 away: within 30 %
		assert.are.equal(30, slider_snap.snap(30, 0, 600, 50))
		assert.are.equal(100, slider_snap.snap(99, 0, 100, 5))
		assert.are.equal(7, slider_snap.snap(7, 0, 100, nil))
		-- detents count from the minimum
		assert.are.equal(11, slider_snap.snap(11, 1, 101, 5))
	end)

	it("steps the wheel to the next detent, or one step when precise", function()
		assert.are.equal(25, slider_snap.wheel(23, 0, 100, 1, 5, 1, false))
		assert.are.equal(20, slider_snap.wheel(23, 0, 100, 1, 5, -1, false))
		assert.are.equal(30, slider_snap.wheel(25, 0, 100, 1, 5, 1, false))
		assert.are.equal(20, slider_snap.wheel(25, 0, 100, 1, 5, -1, false))
		assert.are.equal(24, slider_snap.wheel(23, 0, 100, 1, 5, 1, true))
		assert.are.equal(100, slider_snap.wheel(100, 0, 100, 1, 5, 1, false))
		assert.are.equal(0, slider_snap.wheel(2, 0, 100, 1, 5, -1, false))
		assert.are.equal(4, slider_snap.wheel(3, 1, 16, 1, nil, 1, false))
	end)

	it("reads numbers as the game writes them", function()
		assert.are.equal(2.5, slider_snap.parse_number("2,5 m"))
		assert.are.equal(-3, slider_snap.parse_number("-3 %"))
		assert.are.equal(-3, slider_snap.parse_number("\xE2\x88\x923 %"))
		assert.are.equal(1.5, slider_snap.parse_number("1.5x"))
		assert.is_nil(slider_snap.parse_number("none"))
		assert.is_nil(slider_snap.parse_number(nil))
	end)

	it("finds the position whose label matches a typed value", function()
		local labels = { "-10 m", "-2,5 m", "0 m", "2,5 m", "10 m" }
		assert.are.equal(4, slider_snap.nearest_label(labels, "3"))
		assert.are.equal(2, slider_snap.nearest_label(labels, "-2"))
		assert.are.equal(5, slider_snap.nearest_label(labels, "100"))
		assert.are.equal(2, slider_snap.nearest_label({ "Low", "Medium", "High" }, "me"))
		assert.is_nil(slider_snap.nearest_label({ "Low", "High" }, "x"))
		assert.is_nil(slider_snap.nearest_label(labels, ""))
	end)

	it("puts detents on evenly spaced value lists, anchored at the neutral value", function()
		-- incline: 31 positions of 1 %, 0 % at position 16 -> every 5 positions (5 %)
		assert.are.equal(5, slider_snap.index_detent(31, 16))
		-- bend: 41 positions of 0.05, 0 at 21 -> every 5 (0.25)
		assert.are.equal(5, slider_snap.index_detent(41, 21))
		assert.are.equal(4, slider_snap.index_detent(17, 9))
		assert.is_nil(slider_snap.index_detent(9, 5))
		assert.are.equal(16, slider_snap.snap(17, 1, 31, 5, 16))
		assert.are.equal(21, slider_snap.wheel(17, 1, 31, 1, 5, 1, false, 16))
		assert.are.equal(16, slider_snap.wheel(17, 1, 31, 1, 5, -1, false, 16))
		assert.is_true(slider_snap.evenly_spaced({ -1, -0.5, 0, 0.5, 1 }))
		assert.is_false(slider_snap.evenly_spaced({ -50, -6.25, 0, 6.25, 50 }))
	end)
end)
