local slider_values = require("/ui_overhaul/core/slider_values.lua")

describe("slider_values", function()
	it("keeps values on the slider's grid", function()
		assert.are.equal(5, slider_values.on_grid(4, 1, 59, 2))
		assert.are.equal(3, slider_values.on_grid(3.2, 1, 59, 2))
		assert.are.equal(59, slider_values.on_grid(80, 1, 59, 2))
		assert.are.equal(30, slider_values.on_grid(31, 0, 600, 10))
	end)

	it("moves one step per wheel notch, within the range", function()
		assert.are.equal(24, slider_values.wheel(23, 0, 100, 1, 1))
		assert.are.equal(22, slider_values.wheel(23, 0, 100, 1, -1))
		assert.are.equal(40, slider_values.wheel(30, 0, 600, 10, 1))
		assert.are.equal(100, slider_values.wheel(100, 0, 100, 1, 1))
		assert.are.equal(0, slider_values.wheel(0, 0, 100, 1, -1))
		assert.are.equal(4, slider_values.wheel(3, 1, 16, nil, 1))
	end)

	it("reads numbers as the game writes them", function()
		assert.are.equal(2.5, slider_values.parse_number("2,5 m"))
		assert.are.equal(-3, slider_values.parse_number("-3 %"))
		assert.are.equal(-3, slider_values.parse_number("\xE2\x88\x923 %"))
		assert.are.equal(1.5, slider_values.parse_number("1.5x"))
		assert.is_nil(slider_values.parse_number("none"))
		assert.is_nil(slider_values.parse_number(nil))
	end)

	it("finds the position whose label matches a typed value", function()
		local labels = { "-10 m", "-2,5 m", "0 m", "2,5 m", "10 m" }
		assert.are.equal(4, slider_values.nearest_label(labels, "3"))
		assert.are.equal(2, slider_values.nearest_label(labels, "-2"))
		assert.are.equal(5, slider_values.nearest_label(labels, "100"))
		assert.are.equal(2, slider_values.nearest_label({ "Low", "Medium", "High" }, "me"))
		assert.is_nil(slider_values.nearest_label({ "Low", "High" }, "x"))
		assert.is_nil(slider_values.nearest_label(labels, ""))
	end)
end)
