#!/usr/bin/env python3
"""Writes gui/needs.lua: what each of the mod's GUI modules takes from the base game's modules, so the
installer can leave a feature vanilla when a game update removed something it uses (gui/compat.lua).

For every module in gui/ (not stylesheets, resources or stubs) it lists the fields the code reads from
each base module it requires ("::/..."): `local x = require("::/a/b.tl")` and then `x.Field` in code,
comments and strings left out. A base module the code reads no field from (some modules are a recipe
themselves) is listed with no fields: it only has to load. It also lists the mod's own modules each
one requires, and the modules each feature's plugins render (`guard.plugin(PATH, field, feature)` in
the *.script.lua stubs), so a feature is checked with everything it shows. Not followed: the mod's
infrastructure (INFRASTRUCTURE below: without it nothing installs, so it would make every feature
depend on what it only uses for optional work), and modules loaded with guard.module, which are
optional where they are used. Run by `make content`; CI checks the file is current.

Usage: tools/needs.py"""
import glob, os, re

GUI = "src/ui_overhaul/content/ui_overhaul/gui"
INFRASTRUCTURE = {"priority", "guard", "builtin_wraps", "fallback", "settings", "styles", "installer", "compat"}
OUT = os.path.join(GUI, "needs.lua")

def code_only(text):
    """The Lua source without comments and string contents (strings stay as empty quotes)."""
    out, i, n = [], 0, len(text)
    while i < n:
        if text.startswith("--[[", i) or text.startswith("--[=", i):
            m = re.match(r"--\[(=*)\[", text[i:])
            if m:
                end = text.find("]" + m.group(1) + "]", i)
                i = n if end < 0 else end + len(m.group(1)) + 2
                continue
        if text.startswith("--", i):
            end = text.find("\n", i)
            i = n if end < 0 else end
            continue
        c = text[i]
        if c in "\"'":
            j = i + 1
            while j < n and text[j] != c:
                j += 2 if text[j] == "\\" else 1
            out.append(c + c)
            i = j + 1
            continue
        m = re.match(r"\[(=*)\[", text[i:])
        if m:
            end = text.find("]" + m.group(1) + "]", i)
            out.append('""')
            i = n if end < 0 else end + len(m.group(1)) + 2
            continue
        out.append(c)
        i += 1
    return "".join(out)

def module_name(path):
    m = re.search(r"/ui_overhaul/gui/(\w+)\.lua$", path)
    return m and m.group(1)

modules, requires, plugins = {}, {}, {}
for path in sorted(glob.glob(os.path.join(GUI, "*.lua"))):
    name = os.path.basename(path)[:-4]
    if name.endswith((".css", ".res", ".script")) or name == "needs":
        continue
    text = open(path, encoding="utf-8").read()
    base = dict(re.findall(r'local (\w+) = require\("(::/[^"]+)"\)', text))
    own = sorted({module_name(p) for p in re.findall(r'require\("((?:ui_overhaul_1::)?/ui_overhaul/gui/\w+\.lua)"\)', text)} - {None, name})
    code = code_only(text)
    # fields wrapped by name: priority.chain(module, "field", ...)
    chained = re.findall(r'priority\.chain\((\w+),\s*"(\w+)"', text)
    fields = {}
    for var, base_path in base.items():
        if var in ("react", "builtin"):
            continue  # the framework itself: without it there is no UI to install into
        # x.Field, but not api.engine.util.Field for a module named util
        used = set(re.findall(r"(?<![\w.])" + var + r"\.([A-Za-z_]\w*)", code))
        used |= {field for module, field in chained if module == var}
        used = sorted(used)
        fields[base_path] = sorted(set(fields.get(base_path, [])) | set(used))
    modules[name] = fields
    requires[name] = [m for m in own if m and m not in INFRASTRUCTURE]
for path in sorted(glob.glob(os.path.join(GUI, "*.script.lua"))):
    text = open(path, encoding="utf-8").read()
    consts = dict(re.findall(r'local (\w+) = "([^"]+)"', text))
    for const, _field, feature in re.findall(r'guard\.plugin\((\w+),\s*"(\w+)",\s*"(\w+)"\)', text):
        target = module_name(consts.get(const, ""))
        if target:
            plugins.setdefault(feature, set()).add(target)

def lua_list(items):
    return "{ " + ", ".join(f'"{i}"' for i in items) + " }" if items else "{}"

lines = [
    "--- Generated by tools/needs.py (make content); do not edit. What each GUI module reads from the base",
    "-- game's modules (module -> base path -> fields), the mod's modules each one requires, and the",
    "-- modules each feature's plugins render. gui/compat.lua checks it before a feature installs.",
    "-- @module ui_overhaul.gui.needs",
    "",
    "---@class uo.gui.needs",
    "---@field modules table<string, table<string, string[]>>",
    "---@field requires table<string, string[]>",
    "---@field plugins table<string, string[]>",
    "local needs = {",
    "\tmodules = {",
]
for name in sorted(modules):
    if not modules[name]:
        lines.append(f"\t\t{name} = {{}},")
        continue
    lines.append(f"\t\t{name} = {{")
    for base_path in sorted(modules[name]):
        line = f'\t\t\t["{base_path}"] = {lua_list(modules[name][base_path])},'
        if len(line.expandtabs(4)) <= 120:
            lines.append(line)
        else:  # luacheck's line length: one field per line
            lines.append(f'\t\t\t["{base_path}"] = {{')
            lines.extend(f'\t\t\t\t"{field}",' for field in modules[name][base_path])
            lines.append("\t\t\t},")
    lines.append("\t\t},")
lines.append("\t},")
lines.append("\trequires = {")
for name in sorted(requires):
    if requires[name]:
        lines.append(f"\t\t{name} = {lua_list(requires[name])},")
lines.append("\t},")
lines.append("\tplugins = {")
for feature in sorted(plugins):
    lines.append(f"\t\t{feature} = {lua_list(sorted(plugins[feature]))},")
lines.append("\t},")
lines.append("}")
lines.append("")
lines.append("return needs")
with open(OUT, "w", encoding="utf-8", newline="\n") as handle:
    handle.write("\n".join(lines) + "\n")
print(f"{OUT}: {len(modules)} modules")
